//Viagogo Developer Test Solution By Krisztian Nagy - mxsxs2@gmail.com
package main

//The base currency
const BASECURRENCY = "$"

//The highest coordinate for both X and Y
const COORDMAX = 10

//The lowest coordinate for both X and Y
const COORDMIN = -10

//The number of results to show to the user
const NUMBEROFRESULTS = 5

//As the documentation did not clarify how many events and tickects should I have, I decided to generate random amount of them

//The maximum number of events generated by the data generator
const MAXSEEDDATA = 100

//The minimum number of events generated by the data generator
const MINSEEDDATA = 10

//The maximum number of tickets generated by the data generator for each ticket
const MAXNUMBEROFTICKETS = 50

//The minimum number of tickets generated by the data generator for each ticket
const MINNUMBEROFTICKETS = 10

//The masimum price of a the ticket
const MAXTICKETPRICE = 99
